apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: es-storage
