apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 5601
  selector:
    io.kompose.service: kibana
  type: LoadBalancer
status:
  loadBalancer: {}
